# Generated by Django 2.2.3 on 2021-05-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('duration', models.IntegerField()),
                ('project_image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
