# Generated by Django 2.2.3 on 2021-05-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
