# Generated by Django 2.2.3 on 2021-05-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_task_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
